USE transportation_report;
CREATE TABLE arbs_origins (
    id                     INT AUTO_INCREMENT PRIMARY KEY,
    carrier_forwarder_name VARCHAR(100)   NOT NULL,
    origin_continent       VARCHAR(50)    NOT NULL,
    origin_country         VARCHAR(50)    NOT NULL,
    origin_port            VARCHAR(100)   NOT NULL,
    arb_20ft               DECIMAL(10,2)  NULL,
    arb_40ft               DECIMAL(10,2)  NULL,
    arb_40hc               DECIMAL(10,2)  NULL
);
CREATE TABLE domestic_charges (
    id                      INT AUTO_INCREMENT PRIMARY KEY,
    carrier_forwarder_name  VARCHAR(100)   NOT NULL,
    destination_cy_location VARCHAR(100)   NOT NULL,
    broker_pier_pass        DECIMAL(10,2)  NOT NULL DEFAULT 0,
    wowl_fee                DECIMAL(10,2)  NOT NULL DEFAULT 0,
    toll                    DECIMAL(10,2)  NOT NULL DEFAULT 0,
    gate_fee                DECIMAL(10,2)  NOT NULL DEFAULT 0,
    per_diem_free_days      DECIMAL(10,2)  NOT NULL DEFAULT 0,
    calendar_or_working     VARCHAR(20)    NULL,
    documentation_chrg      DECIMAL(10,2)  NOT NULL DEFAULT 0,
    bol_fee                 DECIMAL(10,2)  NOT NULL DEFAULT 0,
    handling_fee            DECIMAL(10,2)  NOT NULL DEFAULT 0,
    wharfage_chrg           DECIMAL(10,2)  NOT NULL DEFAULT 0,
    pier_pass_chrg_20ft     DECIMAL(10,2)  NOT NULL DEFAULT 0,
    clean_truck_fee_20ft    DECIMAL(10,2)  NOT NULL DEFAULT 0,
    ams_fee_20ft            DECIMAL(10,2)  NOT NULL DEFAULT 0,
    pier_pass_chrg_40ft     DECIMAL(10,2)  NOT NULL DEFAULT 0,
    clean_truck_fee_40ft    DECIMAL(10,2)  NOT NULL DEFAULT 0,
    ams_fee_40ft            DECIMAL(10,2)  NOT NULL DEFAULT 0,
    pier_pass_chrg_40hc     DECIMAL(10,2)  NOT NULL DEFAULT 0,
    clean_truck_fee_40hc    DECIMAL(10,2)  NOT NULL DEFAULT 0,
    ams_fee_40hc            DECIMAL(10,2)  NOT NULL DEFAULT 0
);
CREATE TABLE dray (
    id                              INT AUTO_INCREMENT PRIMARY KEY,
    destination_cy_location         VARCHAR(100)   NULL,
    branch_destination              VARCHAR(100)   NULL,
    drop_live_unload                VARCHAR(20)    NULL,
    trucker                         VARCHAR(100)   NULL,
    dray_base_rate                  DECIMAL(10,2)  NULL,
    drop_fee                        DECIMAL(10,2)  NULL,
    fuel_surcharge_pct              DECIMAL(10,5)  NULL,
    fuel_surcharge_amt              DECIMAL(10,2)  NULL,
    total_dray_1                    DECIMAL(10,2)  NULL,
    emergency_fuel_surcharge_pct    DECIMAL(10,5)  NULL,
    emergency_fuel_surcharge_amt    DECIMAL(10,2)  NULL,
    total_dray_2                    DECIMAL(10,2)  NULL,
    diane_fuel_surcharge_pct        DECIMAL(10,5)  NULL,
    diane_fuel_surcharge_amt        DECIMAL(10,2)  NULL,
    total_dray_3                    DECIMAL(10,2)  NULL,
    chassis_charge_per_day          DECIMAL(10,2)  NULL,
    chassis_split_charge            VARCHAR(50)    NULL,
    prepull                         DECIMAL(10,2)  NULL,
    yard_storage_if_applicable      DECIMAL(10,2)  NULL,
    free_hours                      VARCHAR(20)    NULL,
    per_hour_charge_after_free_time DECIMAL(10,2)  NULL,
    layover_charge                  DECIMAL(10,2)  NULL,
    stop_off_fee                    DECIMAL(10,2)  NULL,
    port_congestion                 DECIMAL(10,2)  NULL,
    toll_charge                     DECIMAL(10,2)  NULL,
    port_rail_driver_wait_time      VARCHAR(20)    NULL,
    port_rail_driver_chrg           DECIMAL(10,2)  NULL,
    desc_of_misc_chrg               VARCHAR(255)   NULL,
    misc_chrg_not_mentioned         VARCHAR(50)    NULL
);
CREATE TABLE carrier_schema (
    id                                  INT AUTO_INCREMENT PRIMARY KEY,
    effective_date                      DATE            NOT NULL,
    end_date                            DATE            NOT NULL,
    carrier_type                        VARCHAR(10)     NOT NULL,
    carrier_forwarder_name              VARCHAR(100)    NOT NULL,
    origin_continent                    VARCHAR(50)     NOT NULL,
    origin_country                      VARCHAR(50)     NOT NULL,
    origin_port                         VARCHAR(100)    NOT NULL,
    destination_port_of_discharge_coast VARCHAR(20)     NOT NULL,
    destination_port_of_discharge       VARCHAR(100)    NOT NULL,
    move_ipi_ripi_cy                    VARCHAR(20)     NOT NULL,
    destination_cy_location             VARCHAR(100)    NOT NULL,
    ocean_freight_base_charge_20ft      DECIMAL(10,2)   NOT NULL DEFAULT 0,
    pss_20ft                            DECIMAL(10,2)   NOT NULL DEFAULT 0,
    emergency_fuel_surcharge_20ft       DECIMAL(10,2)   NOT NULL DEFAULT 0,
    isps_charge_20ft                    DECIMAL(10,2)   NOT NULL DEFAULT 0,
    security_charge_20ft                DECIMAL(10,2)   NOT NULL DEFAULT 0,
    war_risk_20ft                       DECIMAL(10,2)   NOT NULL DEFAULT 0,
    epc_charge_20ft                     DECIMAL(10,2)   NOT NULL DEFAULT 0,
    ets_20ft                            DECIMAL(10,2)   NOT NULL DEFAULT 0,
    admin_charge_20ft                   DECIMAL(10,2)   NOT NULL DEFAULT 0,
    bunker_20ft                         DECIMAL(10,2)   NOT NULL DEFAULT 0,
    low_sulfur_20ft                     DECIMAL(10,2)   NOT NULL DEFAULT 0,
    cuc_20ft                            DECIMAL(10,2)   NOT NULL DEFAULT 0,
    gri_20ft                            DECIMAL(10,2)   NOT NULL DEFAULT 0,
    erc_20ft                            DECIMAL(10,2)   NOT NULL DEFAULT 0,
    emergency_intermodel_20ft           DECIMAL(10,2)   NOT NULL DEFAULT 0,
    alameda_corridor_20ft               DECIMAL(10,2)   NOT NULL DEFAULT 0,
    suez_canal_20ft                     DECIMAL(10,2)   NOT NULL DEFAULT 0,
    panama_canal1_20ft                  DECIMAL(10,2)   NOT NULL DEFAULT 0,
    labor_surcharge_20ft                DECIMAL(10,2)   NOT NULL DEFAULT 0,
    additional_charge_1_20ft            DECIMAL(10,2)   NOT NULL DEFAULT 0,
    additional_charge_2_20ft            DECIMAL(10,2)   NOT NULL DEFAULT 0,
    ocean_freight_base_charge_40ft      DECIMAL(10,2)   NOT NULL DEFAULT 0,
    pss_40ft                            DECIMAL(10,2)   NOT NULL DEFAULT 0,
    emergency_fuel_surcharge_40ft       DECIMAL(10,2)   NOT NULL DEFAULT 0,
    isps_charge_40ft                    DECIMAL(10,2)   NOT NULL DEFAULT 0,
    security_charge_40ft                DECIMAL(10,2)   NOT NULL DEFAULT 0,
    war_risk_40ft                       DECIMAL(10,2)   NOT NULL DEFAULT 0,
    epc_charge_40ft                     DECIMAL(10,2)   NOT NULL DEFAULT 0,
    ets_40ft                            DECIMAL(10,2)   NOT NULL DEFAULT 0,
    admin_charge_40ft                   DECIMAL(10,2)   NOT NULL DEFAULT 0,
    bunker_40ft                         DECIMAL(10,2)   NOT NULL DEFAULT 0,
    low_sulfur_40ft                     DECIMAL(10,2)   NOT NULL DEFAULT 0,
    cuc_40ft                            DECIMAL(10,2)   NOT NULL DEFAULT 0,
    gri_40ft                            DECIMAL(10,2)   NOT NULL DEFAULT 0,
    erc_40ft                            DECIMAL(10,2)   NOT NULL DEFAULT 0,
    emergency_intermodel_40ft           DECIMAL(10,2)   NOT NULL DEFAULT 0,
    alameda_corridor_40ft               DECIMAL(10,2)   NOT NULL DEFAULT 0,
    suez_canal_40ft                     DECIMAL(10,2)   NOT NULL DEFAULT 0,
    panama_canal_40ft                   DECIMAL(10,2)   NOT NULL DEFAULT 0,
    labor_surcharge_40ft                DECIMAL(10,2)   NOT NULL DEFAULT 0,
    additional_charge_1_40ft            DECIMAL(10,2)   NOT NULL DEFAULT 0,
    additional_charge_2_40ft            DECIMAL(10,2)   NOT NULL DEFAULT 0,
    ocean_freight_base_charge_40hc      DECIMAL(10,2)   NOT NULL DEFAULT 0,
    pss_40hc                            DECIMAL(10,2)   NOT NULL DEFAULT 0,
    emergency_fuel_surcharge_40hc       DECIMAL(10,2)   NOT NULL DEFAULT 0,
    isps_charge_40hc                    DECIMAL(10,2)   NOT NULL DEFAULT 0,
    security_charge_40hc                DECIMAL(10,2)   NOT NULL DEFAULT 0,
    war_risk_40hc                       DECIMAL(10,2)   NOT NULL DEFAULT 0,
    epc_charge_40hc                     DECIMAL(10,2)   NOT NULL DEFAULT 0,
    ets_40hc                            DECIMAL(10,2)   NOT NULL DEFAULT 0,
    admin_charge_40hc                   DECIMAL(10,2)   NOT NULL DEFAULT 0,
    bunker_40hc                         DECIMAL(10,2)   NOT NULL DEFAULT 0,
    low_sulfur_40hc                     DECIMAL(10,2)   NOT NULL DEFAULT 0,
    cuc_40hc                            DECIMAL(10,2)   NOT NULL DEFAULT 0,
    gri_40hc                            DECIMAL(10,2)   NOT NULL DEFAULT 0,
    erc_40hc                            DECIMAL(10,2)   NOT NULL DEFAULT 0,
    emergency_intermodel_40hc           DECIMAL(10,2)   NOT NULL DEFAULT 0,
    alameda_corridor_40hc               DECIMAL(10,2)   NOT NULL DEFAULT 0,
    suez_canal_40hc                     DECIMAL(10,2)   NOT NULL DEFAULT 0,
    panama_canal_40hc                   DECIMAL(10,2)   NOT NULL DEFAULT 0,
    labor_surcharge_40hc                DECIMAL(10,2)   NOT NULL DEFAULT 0,
    additional_charge_1_40hc            DECIMAL(10,2)   NOT NULL DEFAULT 0,
    additional_charge_2_40hc            DECIMAL(10,2)   NOT NULL DEFAULT 0
);
CREATE TABLE msc   	   LIKE carrier_schema;
CREATE TABLE `one` 	   LIKE carrier_schema;
CREATE TABLE evergreen LIKE carrier_schema;
CREATE TABLE wan_hai   LIKE carrier_schema;
CREATE TABLE sm_line   LIKE carrier_schema;
DROP TABLE carrier_schema;
CREATE TABLE origin_charges (
    id                              INT AUTO_INCREMENT PRIMARY KEY,
    customer_name                   VARCHAR(100)   NOT NULL,
    vendor_name                     VARCHAR(100)   NOT NULL,
    inco_terms                      VARCHAR(50)    NOT NULL,
    origin_port                     VARCHAR(100)   NOT NULL,
    branch_destination              VARCHAR(100)   NOT NULL,
    move                            VARCHAR(20)    NOT NULL,
    orc_20ft                        DECIMAL(10,2)  NOT NULL DEFAULT 0,
    seal_20ft                       DECIMAL(10,2)  NOT NULL DEFAULT 0,
    doc_20ft                        DECIMAL(10,2)  NOT NULL DEFAULT 0,
    ams_20ft                        DECIMAL(10,2)  NOT NULL DEFAULT 0,
    vgm_20ft                        DECIMAL(10,2)  NOT NULL DEFAULT 0,
    trucking_fee_20ft               DECIMAL(10,2)  NOT NULL DEFAULT 0,
    customs_fee_20ft                DECIMAL(10,2)  NOT NULL DEFAULT 0,
    weighing_fee_20ft               DECIMAL(10,2)  NOT NULL DEFAULT 0,
    handling_20ft                   DECIMAL(10,2)  NOT NULL DEFAULT 0,
    eir_20ft                        DECIMAL(10,2)  NOT NULL DEFAULT 0,
    cntr_pickup_other_depot_20ft    DECIMAL(10,2)  NOT NULL DEFAULT 0,
    cntr_pickup_outer_storage_20ft  DECIMAL(10,2)  NOT NULL DEFAULT 0,
    hbl_tlx_release_20ft            DECIMAL(10,2)  NOT NULL DEFAULT 0,
    inspection_20ft                 DECIMAL(10,2)  NOT NULL DEFAULT 0,
    fumigation_20ft                 DECIMAL(10,2)  NOT NULL DEFAULT 0,
    infrastructure_20ft             DECIMAL(10,2)  NOT NULL DEFAULT 0,
    lift_on_20ft                    DECIMAL(10,2)  NOT NULL DEFAULT 0,
    orc_40ft                        DECIMAL(10,2)  NOT NULL DEFAULT 0,
    seal_40ft                       DECIMAL(10,2)  NOT NULL DEFAULT 0,
    doc_40ft                        DECIMAL(10,2)  NOT NULL DEFAULT 0,
    ams_40ft                        DECIMAL(10,2)  NOT NULL DEFAULT 0,
    vgm_40ft                        DECIMAL(10,2)  NOT NULL DEFAULT 0,
    trucking_fee_40ft               DECIMAL(10,2)  NOT NULL DEFAULT 0,
    customs_fee_40ft                DECIMAL(10,2)  NOT NULL DEFAULT 0,
    weighing_fee_40ft               DECIMAL(10,2)  NOT NULL DEFAULT 0,
    handling_40ft                   DECIMAL(10,2)  NOT NULL DEFAULT 0,
    eir_40ft                        DECIMAL(10,2)  NOT NULL DEFAULT 0,
    cntr_pickup_other_depot_40ft    DECIMAL(10,2)  NOT NULL DEFAULT 0,
    cntr_pickup_outer_storage_40ft  DECIMAL(10,2)  NOT NULL DEFAULT 0,
    hbl_tlx_release_40ft            DECIMAL(10,2)  NOT NULL DEFAULT 0,
    inspection_40ft                 DECIMAL(10,2)  NOT NULL DEFAULT 0,
    fumigation_40ft                 DECIMAL(10,2)  NOT NULL DEFAULT 0,
    infrastructure_40ft             DECIMAL(10,2)  NOT NULL DEFAULT 0,
    lift_on_40ft                    DECIMAL(10,2)  NOT NULL DEFAULT 0,
    orc_40hc                        DECIMAL(10,2)  NOT NULL DEFAULT 0,
    seal_40hc                       DECIMAL(10,2)  NOT NULL DEFAULT 0,
    doc_40hc                        DECIMAL(10,2)  NOT NULL DEFAULT 0,
    ams_40hc                        DECIMAL(10,2)  NOT NULL DEFAULT 0,
    vgm_40hc                        DECIMAL(10,2)  NOT NULL DEFAULT 0,
    trucking_fee_40hc               DECIMAL(10,2)  NOT NULL DEFAULT 0,
    customs_fee_40hc                DECIMAL(10,2)  NOT NULL DEFAULT 0,
    weighing_fee_40hc               DECIMAL(10,2)  NOT NULL DEFAULT 0,
    handling_40hc                   DECIMAL(10,2)  NOT NULL DEFAULT 0,
    eir_40hc                        DECIMAL(10,2)  NOT NULL DEFAULT 0,
    cntr_pickup_other_depot_40hc    DECIMAL(10,2)  NOT NULL DEFAULT 0,
    cntr_pickup_outer_storage_40hc  DECIMAL(10,2)  NOT NULL DEFAULT 0,
    hbl_tlx_release_40hc            DECIMAL(10,2)  NOT NULL DEFAULT 0,
    inspection_40hc                 DECIMAL(10,2)  NOT NULL DEFAULT 0,
    fumigation_40hc                 DECIMAL(10,2)  NOT NULL DEFAULT 0,
    infrastructure_40hc             DECIMAL(10,2)  NOT NULL DEFAULT 0,
    lift_on_40hc                    DECIMAL(10,2)  NOT NULL DEFAULT 0
);
CREATE TABLE forwarder_spot_schema (
    id                                  INT AUTO_INCREMENT PRIMARY KEY,
    effective_date                      DATE           NOT NULL,
    end_date                            DATE           NOT NULL,
    carrier_type                        VARCHAR(10)    NOT NULL,
    carrier_forwarder_name              VARCHAR(100)   NOT NULL,
    origin_continent                    VARCHAR(50)    NOT NULL,
    origin_country                      VARCHAR(50)    NOT NULL,
    origin_port                         VARCHAR(100)   NOT NULL,
    destination_port_of_discharge_coast VARCHAR(20)    NOT NULL,
    destination_port_of_discharge       VARCHAR(100)   NOT NULL,
    move_ipi_ripi_cy                    VARCHAR(20)    NOT NULL,
    destination_cy_location             VARCHAR(100)   NOT NULL,
    ocean_freight_base_charge_20ft      DECIMAL(10,2)  NOT NULL DEFAULT 0,
    admin_charge_20ft                   DECIMAL(10,2)  NOT NULL DEFAULT 0,
    additional_charge_20ft              DECIMAL(10,2)  NOT NULL DEFAULT 0,
    ocean_freight_base_charge_40ft      DECIMAL(10,2)  NOT NULL DEFAULT 0,
    admin_charge_40ft                   DECIMAL(10,2)  NOT NULL DEFAULT 0,
    additional_charge_40ft              DECIMAL(10,2)  NOT NULL DEFAULT 0,
    ocean_freight_base_charge_40hc      DECIMAL(10,2)  NOT NULL DEFAULT 0,
    admin_charge_40hc                   DECIMAL(10,2)  NOT NULL DEFAULT 0,
    additional_charge_40hc              DECIMAL(10,2)  NOT NULL DEFAULT 0
);
CREATE TABLE forwarders LIKE forwarder_spot_schema;
CREATE TABLE spot       LIKE forwarder_spot_schema;
DROP TABLE forwarder_spot_schema;

